### ISSUE TITLE
security.alternate-file-domain causing problems with phame

### ISSUE THREAD

**Issue by pulkitjalan** [phacility/phabricator#463]
Hi,

I just configured the 'security.alternate-file-domain' config and setup the vhosts appropriately. Everything is working properly, except for phame. Im getting an error when I go to Live Blog, looks like it cant load the oblivious.css.

[Exception] This Phabricator install is configured as "https://phabricator.example.com/", but you are accessing it via "phabricator-files.example.com". Acccess Phabricator via the primary configured domain. Phabricator will not set cookies on other domains for security reasons.

Do I need to add the 'security.alternate-file-domain' as one of the 'phabricator.allowed-uris'?

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
