### ISSUE TITLE
Audit inline comments are missing/wrong on git merge commits

### ISSUE THREAD

**Issue by motownread** [phacility/phabricator#564]
Steps to reproduce:

On branch master:
```
git checkout -b branch1
echo foo > bar
git add .
git commit -m 'commit1'
git checkout master
git merge --no-ff branch1
git push
```

In diffusion view the merge commit and add an inline comment to the file 'bar' at line 1, add a commit comment, and save.

Now view the merge commit again. The commit comment and the inline comment are listed correctly, but the inline comment is not shown in the diff for the file 'bar'.

Now in diffusion view the first commit on the branch ('commit1'). Add an inline comment to 'bar' at line 1, add a commit comment, and save.

Now view the **merge** commit again. Still the commit and inline comments are listed correctly, but now the inline comment from **'commit1'** is shown in the diff for the file 'bar'!

This is a shame since merge commits are a good place to audit entire branches, but the inline comments don't show correctly.

Thanks.

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
