### ISSUE TITLE
Daemon fails to parse SVN Folder with Whitespace

### ISSUE THREAD

**Issue by trialgod** [phacility/phabricator#583]
Hi,

we try to use Phabricator for our .NET Repositorys.

Since the import of our repository takes a long time, i've tried to investigate this issue. 

The daemon error log shows this:
STDERR
svn: Unable to parse URL '/svn/Web/!svn/bc/6680/Lernende/Webanwendung/VS/Webanwendung/Service References/'
 at [/var/www/phabricator/libphutil/src/future/exec/ExecFuture.php:398]
  #0 ExecFuture::resolvex() called at [/var/www/phabricator/phabricator/src/applications/repository/storage/PhabricatorRepository.php:253]
  #1 PhabricatorRepository::execxRemoteCommand(--xml ls %C, '[..]/svn/Web/Lernende/Webanwendung/VS/Webanwendung@6680' '[..]/svn/Web/Lernende/Webanwendung/VS/Webanwendung/Firma@6680' [..]/svn/Web/Lernende/Webanwendung/VS/Webanwendung/App_Data@6679' '[..]/svn/Web/Lernende/Webanwendung/VS/Webanwendung/Administration@6680') called at [/var/www/phabricator/phabricator/src/applications/repository/worker/commitchangeparser/PhabricatorRepositorySvnCommitChangeParserWorker.php:592]
  #2 PhabricatorRepositorySvnCommitChangeParserWorker::lookupPathFileTypes(Object PhabricatorRepository, Array of size 8 starting with: { /Lernende/Webanwendung/VS/Webanwendung/Administration/PersonenListe.aspx.cs => Array of size 2 starting with: { rawPath => /Lernende/Webanwendung/VS/Webanwendung/Administration/PersonenListe.aspx.cs } }) called at [/var/www/phabricator/phabricator/src/applications/repository/worker/commitchangeparser/PhabricatorRepositorySvnCommitChangeParserWorker.php:121]
  #3 PhabricatorRepositorySvnCommitChangeParserWorker::parseCommitChanges(Object PhabricatorRepository, Object PhabricatorRepositoryCommit) called at [/var/www/phabricator/phabricator/src/applications/repository/worker/commitchangeparser/PhabricatorRepositoryCommitChangeParserWorker.php:30]
  #4 PhabricatorRepositoryCommitChangeParserWorker::parseCommit(Object PhabricatorRepository, Object PhabricatorRepositoryCommit) called at [/var/www/phabricator/phabricator/src/applications/repository/worker/PhabricatorRepositoryCommitParserWorker.php:44]
  #5 PhabricatorRepositoryCommitParserWorker::doWork() called at [/var/www/phabricator/phabricator/src/infrastructure/daemon/workers/PhabricatorWorker.php:85]
  #6 PhabricatorWorker::executeTask() called at [/var/www/phabricator/phabricator/src/infrastructure/daemon/workers/storage/PhabricatorWorkerActiveTask.php:123]
  #7 PhabricatorWorkerActiveTask::executeTask() called at [/var/www/phabricator/phabricator/src/infrastructure/daemon/workers/PhabricatorTaskmasterDaemon.php:19]
  #8 PhabricatorTaskmasterDaemon::run() called at [/var/www/phabricator/libphutil/src/daemon/PhutilDaemon.php:85]
  #9 PhutilDaemon::execute() called at [/var/www/phabricator/libphutil/scripts/daemon/exec/exec_daemon.php:112]

Thank you.

**Comment by marutib** [comment]
Yup same here

**Comment by chadlittle** [comment]
Tracking in https://secure.phabricator.com/T6891

**Comment by chadlittle** [comment]
Just to gather additional information, what svn client are you using on the server? I am told that SVN 1.8 or newer should be used.
