### ISSUE TITLE
svn importing hangs at 99.99%

### ISSUE THREAD

**Issue by kylejao** [phacility/phabricator#626]
There are three queued tasks, but it seems no daemon is working on any of them. All queued tasks have PhabricatorRepositorySvnCommitChangeParserWorker as the task class.

The output of '$ ./bin/repository importing J' is

rJ28601 Change, Owners, Herald
rJ48280 Change, Owners, Herald
rJ48281 Change, Owners, Herald

I tried running

$ ./scripts/repository/reparse.php --message --change --owners --herald --force rJ28601 --trace

but it hangs after executing 27 commands. output see 
https://secure.phabricator.com/file/data/jrslofb6v4pb5gwotwck/PHID-FILE-mmb7glkb6x43kpgpvzhx/output
(repo address has been mocked)

I found that the 27th execution is like running forever.  The size of the file it downloads (/tmp/exum2erivf4888kw/12087-CTaAKn in this case) has been already more than 3 GB. I'm not sure if it's due to a bug or the commit information is really that much.

Does anyone know how to fix this? Thanks.

**Comment by chadlittle** [comment]
Closing, assume resolved. Open ticket on https://secure.phabricator.com if assistance is still needed.
