### ISSUE TITLE
New repository access error for signers of legalpad documents [enhancement] [question]

### ISSUE THREAD

**Issue by uaoleg** [phacility/phabricator#639]
If the custom policy **signers of legalpad documents** for creating new repositories is set, it would be nice to display the link on this document for those users, who hasn't signed them yet.

Now it isn't clear, what the user should make to get access: http://joxi.ru/c7eWUxjKTJBwH3xVpg4

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
