### ISSUE TITLE
Daemon rejects svn self-signed cert but manual connections accept them.

### ISSUE THREAD

**Issue by JasonLane** [phacility/phabricator#683]
I've recently installed Phabricator on a new Ubuntu 14.04 vm and connected it to our in house svn repo server over https. Importing the repo failed until I permanently accepted the cert from the svn repo from the command line after running:

svn list https://svn-repos.company.com/svn/Research/

The import has stalled out at 85% and when I try to access any of the documents from Diffusion I get this error:

Unhandled Exception ("CommandException")
Command failed with error #1!
COMMAND
svn --non-interactive --no-auth-cache --trust-server-cert --username 'xxxxx' --password 'xxxxx' cat 'https://svn-repos.company.com/svn/Research/stuff/trunk/README.txt@1228'

STDOUT
(empty)

STDERR
svn: OPTIONS of 'https://svn-repos.company.com/svn/Research/stuff/trunk/README.txt': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://xxxxx

After much googling, my issue looks uncomfortably like 'svn + phabricator #464'.  I've permanently accepted the certificate as the user running Phabricator, still no joy. I've run all of the commands suggested for troubleshooting from #464 with similar/identical results. Specifically my issue is:

"I don't know why it's being accepted when I run commands manually and rejected by the daemon."

Update:
The stalled Import activity followed with the failure to open any files (browsing folders works just fine) suggests that the daemon accepted the certificate at one point, but now it doesn't. Any way to re-establish the daemon's trust in the cert, and/or restart the import?

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
