### ISSUE TITLE
Commenting ability locked after attempting to add self reviewer

### ISSUE THREAD

**Issue by skalidindi3** [phacility/phabricator#686]
After trying to add myself as a reviewer on a Diff, I got a `Validation error` with the comment: `The author of a revision can not be a reviewer.`. After switching my action back to `Comment`, I am still receiving this error.

Tried switching to a Chrome Incognito window, signing in, and commenting: problem still persists. I seem to have screwed myself out of being able to comment on my Diff at this point :D

**Comment by chadlittle** [comment]
Tracking in https://secure.phabricator.com/T6989
