### ISSUE TITLE
/differential.createrawdiff can't handle binary files

### ISSUE THREAD

**Issue by ptarjan** [phacility/phabricator#697]
If I have a diff with something like this

```
diff --git a/hphp/test/slow/archive_handler/tar_archive.tar b/hphp/test/slow/archive_handler/tar_archive.tar
new file mode 100644
index 0000000000000000000000000000000000000000..e51f4b8b8e8ebdf50f96e2113d1073ff97fef968
GIT binary patch
literal 10240
zcmeIyy$*sf5C`x+3QvG7AgsDGIJh`9XQ)a<FxMKzrx)T!#6c%W)c*~X_F8Cu&D9_I
zqe)to>ohO7qMwjW#8D*Lwu#qPs&R53yXKXOWh}h3pY3$Nda#bz^8{Cw>t?#WPx<cb
zuj#FrcIH^|R=Z8k*`C<d`fSQfJEqbW<cwy@3tQ8!&_%vv;#$uixoJjwXZU%wT`g{N
z_4Rc|Yz_PF^cMJQ$bM?0L!5tG)bHxQy%SUrCMryVFbafh9+48B976if>wgGh`~w0I
wfB*y_009U<00Izz00bZa0SG_<0uX=z1Rwwb2tWV=5P$##AOHafK%hT?3!w*j_y7O^

literal 0
HcmV?d00001
```

If I call `createrawdiff` with that, then the thing I get back when calling `differential.getrawdiff` is

```
diff --git a/hphp/test/slow/archive_handler/tar_archive.tar b/hphp/test/slow/archive_handler/tar_archive.tar
new file mode 100644
index 0000000000000000000000000000000000000000..0000000000000000000000000000000000000000
GIT binary patch
literal 0
Hc$@<O00001

literal 0
Hc$@<O00001
```

How can I get this binary file into phabricator?

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
