### ISSUE TITLE
arc diff fails in git if submodules have changes

### ISSUE THREAD

**Issue by skrap** [phacility/phabricator#704]
arc diff fails in git if submodules have changes

Arcanist seems to use git stash to try to bottle up working copy changes.  This doesn't work in the case of submodules, and will prevent users who have dirty submodules from using arcanist.

To repro:
 cd /tmp
 git init sub
 git init main
 cd sub
 echo "A first commit" > README
 git add README 
 git commit -m "First commit in sub repo."
 cd ../main
 git submodule add ../sub/
 git commit -m "Adding submodule."
 echo "some change" >> sub/README 
 arc diff

At this point, arc diff will notice that the submodule has changes, and try to stash them.  Git stash doesn't affect submodules, so it arc will fail when it sees that the working copy is still dirty.  I'd expect arcanist to ignore dirty submodules when considering whether a repository is in a dirty state, as arcanist doesn't deal in submodules anyways.

The "--ignore-submodules" switch to git status might be of use here.

**Comment by chadlittle** [comment]
Presume this identical to https://secure.phabricator.com/T3065
