### ISSUE TITLE
arc commit failed due to incorrect PWD when sudo from vcs-user to daemon-user

### ISSUE THREAD

**Issue by likan999** [phacility/phabricator#715]
Hi I am not sure why nobody else reported the issue, but what happened to me was, I set up SVN repository in phabricator with the guide and I carefully verified everything was ok using the test commands in the user's guide, and 'arc diff' and code reviews were working properly, however, it failed at 'arc commit' with mysterious error message:
svn: E165001: Commit blocked by pre-commit hook (exit code 255) with no output.

After spending a lot of time to dig into it, I found the root cause was:
1) on client side, if we run `arc commit`, it will essentially SSH into server using vcs-user;
2) on server side, once logged in, it will `sudo` to 'daemon-users' to run 'svnserve -t';
3) the PWD after sudo is still /home/vcs-user,
4) in svnserve, when it forks and runs the pre-commit hook, strace shows it will first run `chdir(".")`;
5) since PWD is not accessible by daemon-users, pre-commit hook fails with no error message.

If I simply set /home/vcs-user to be accessible to everyone, and then 'arc commit' will succeed.  So this confirms it is the root cause.

Now my question is, is this issue awared by you guys?  What's the best way to fix it now, as adding 'x' bit for /home/vcs-user is not very nice?  Thanks.

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
