### ISSUE TITLE
Ability to lock user names when doing LDAP login

### ISSUE THREAD

**Issue by mboudreau** [phacility/phabricator#790]
We have this issue at work when people are first registering for an account using our LDAP, that they can still change their username and real name, even if the LDAP version should be providing this.  This causes people to create 'non-standard' usernames and makes it very hard to add them as reviewers on 'arc diff'.

If would be great if this could be pre-filled and locked (or the page skipped altogether) to ensure that everyone is employing the same standard.

Cheers.

**Comment by epriestley** [comment]
You can use the `PhabricatorEventType::TYPE_AUTH_WILLREGISTERUSER` event to enforce this. See <https://secure.phabricator.com/book/phabricator/article/events/>. Events are mostly on the way out and not hugely well documented, but there might be enough information there to get you started.

Administrators can also change users' usernames after the fact.

You could also solve this with a social/policy solution, like "use the same names in this system or you're fired".

If you need more specific documentation on the event stuff, see this document for instructions on filing a feature request:

https://secure.phabricator.com/book/phabcontrib/article/feature_requests/
