### ISSUE TITLE
Error PHABRICATOR_USER should be defined

### ISSUE THREAD

**Issue by Kara4un** [phacility/phabricator#792]
Hi,

I have an error, when pushing my commits from local repo to server. It seems like this

$git push
spimenov@phabricator.tsi.ru's password:
Counting objects: 19 done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects^ 100% (10/10), 656 bytes | - bytes/s, done.
Total 10 (delta 3), refused 0 (delta 0)
remote [2015-01-21 17:20:35] EXCEPTION: (Exception) usage: PHABRICATOR_USER sho
ild be defined! at [<phabricator>/scripts/repository/commit_hook.php:36]
remote:
To spimenov@phabricator.tsi.ru:/opt/git/tts.git
! [remote rejected] 4.5 -> 4.5 (pre-receive hook declined)
error^ failed to push some refs to 'spimenov@phabricator.tsi.ru:/opt/git/tts.git'

1) I have a virtual server with git, before i install phabricator i could normally do push/pull, checkout, etc.
2) Then I install phabricator (the same server with my git repos) and use configuration guide and advanced guide, at the and i have web phabricator with no issues, i config outbound emails and some other features. Then I started with deffusion
3) I configure daemon-user and vcs-user to use ssh protocol. Maybe important, I start SSH to phabricator on 222 port, and 22 for my putty client.
4) I press new repository. press Import an Existing External Repository, type-GIT, name - TTS, callsign - T
5) Remote URI ssh://vcs-user@phabricator.tsi.ru:222/opt/git/tts.git (I check, that from my putty I can login with vcs-user and can do this git command on 222 port without password (i install assymetric rsa)). In Authentication tab I choose correct private key for my vcs-user
6) Then I continue to config it. Hosting Hosted -> Host on phabricator, ssh -> read/write. Storage Path /opt/git/tts.git (is it right??).

Finally I can see all src, tags, branches and commits, etc.
But when I try to push from my local I have an error. What can it be?

PS my pre-recieve-phabricator.d is empty (except of README), and I dont need custom hooks now.

Thank you and sorry for my english )

**Comment by avivey** [comment]
When hosting a repo in phabricator, the uri should be something like
ssh://vcs-user@phabricator.tsi.ru:222/diffusion/T/tts.git - copy it from the repository's page in phabricator.

Password authentication should also not be available, if hosting is configured correctly - only ssh keys configured in phabricator should work.

It looks like you're connecting using the wrong ssh daemon.

phabricator installs it's hook in the hosted repo, which is why it's trying to run even though the ssh connection is passing through it.

**Comment by Kara4un** [comment]
When I do this

6) Then I continue to config it. Hosting Hosted -> Host on phabricator, ssh -> read/write. Storage Path /opt/git/tts.git (is it right??).

My clone ssh automatically changes to:
git clone ssh://vcs-user@phabricator.tsi.ru:222/diffusion/T/tts.git
When storage is /opt/git/tts.git

Unfortunately, I cannot understand what does ssh://vcs-user@phabricator.tsi.ru:222/diffusion/T/tts.git, becouse I have no /deffusion folder on my server root. On the other hand I can see al code and brunches, becouse of my storage is in /opt/git/tts.git where my git repo locates. So the question, what does this ssh link means?

How can I check if my ssh daemon config correctly? I try to do some clones from the standart command line, and ssh daemon for vcs-user and daemon-user on 222 port works well.

**Comment by avivey** [comment]
/diffusion/ is a virtual path, that is managed by phabricator; It only works when the sshd is set up correctly.

https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/#troubleshooting-ssh can help you debug the issue.
Specifically, try `ssh -T -p 222 vcs-user@phabricator.tsi.ru` and see if you get the right message.

**Comment by Kara4un** [comment]
Ok, I try it, but have no answer. It's meen, i suppose, that i have wrong ssh config. Hope, that you can help me a little.

1) The first question is:  ssh -T -p 222 vcs-user@phabricator.tsi.ru - from what user i should exec this command? I've tried from my root user.

2) If I understand right, when I connect to 222 port, phabricator-ssh-hook.sh should automatically start ssh-auth script. I've tried to start it manually and result was

$ ./phabricator-ssh-hook.sh vcs-user
No keys found.

3) I could not understand this "To authenticate over SSH, users should add SSH Public Keys in the Settings screen." This is about web phabricator page. Now I have 5 web accaunts, and no keys. I can generate key-pair, or upload, but I couldn't understand how my linux vcs-user ssh certs correspond to my web accaunts certs.

I can generate key-pair with web form, and save public part. But where should I past it?

**Comment by Kara4un** [comment]
UPD.

Hmmm... I understand the terrible mistake. When I started to config ssh to phabricator, I manually generate pair of rsa keys and install them to my linux server for vcs-user. I think that I need installed certeficate to connect via ssh. Now I understand that only certificate that i need I should generate via phabricator web form. I delete my manually generated keypair, then i create vcs-user accaunt on my phabricator.tsi.ru and generate new keypair (I can download private key, but can't understand, where i should install this private part of keypair)

Now, I have
```
[vcs-user@phabricator libexec]$ ./phabricator-ssh-hook.sh vcs-user
command="'/opt/phabricator/phabricator/bin/ssh-exec' --phabricator-ssh-user 'vcs-user'",no-port
forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQC7q8E6A7s72wwQx+JGTRmVS7cxC35ZgEm6yotO3oTvI
BkKKWO+4IEpKLLDWDhUj3vL3xLxv1jApATZp4GC+VhUJqvHvAkS2xyGy22IJTSkMad8/OmhwJIw
HdZfNHTlDJsbg4MQCDh43K50M32L1CTwWhkNiQ25ETRiV4sPT7cyaAQQsNDI/lxu10oqVSnx0ql6
Y0pHd8jahnE2Q1r65ogLWm0cUqS/QyuIocGBSNSh0PAofMlsxoXnGkH07IJhMpO1PKgPvtaK8snN
+aGFp6WOyQgaOxnEdtbIuWwWcBinOJtdqckd+6KCOW1OnugZFAGcuRvI3ryLUuiyFl1j
```
and
```
[vcs-user@phabricator libexec]$ ssh -T -p 222 vcs-user@phabricator.tsi.ru
Permission denied (publickey,keyboard-interactive).
```

**Comment by avivey** [comment]
When connecting to phabricator's sshd, you're trying to log into phabricator, using ssh keys. 

Your private key goes in the computer you're connecting from, and the public key goes in phabricator, in the account you're trying to connect to.

You can specify a specific key for ssh to use with `-i private-key-file` (See http://askubuntu.com/questions/30788/does-ssh-key-need-to-be-named-id-rsa for more options).

vcs-user is not a phabricator user, and should not have any keys configured. The linux certs and users are not related to the phabricator certs and users.

Since you get the error "keyboard-interactive" from ssh, you've probably didn't set the right sshd configuration - the right configuration prevents password identification.

**Comment by Kara4un** [comment]
Finally I finish this battle. 

Yeah, the problem was so easy, but as for me, https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/#troubleshooting-ssh wasn't clear. It tells nothing about how to use "settings -> ssh public keys" in web form and where should I install private part of this key.

I understand, that phabricator hooks connection with specific script, than calls ssh-auth php script, then call ssh-exec php script. In this scripts we can see. that it automatically use phabricator internal scripts. But in docs I can find only few words about this principals. 

Finally in my local repo I use clone command like git clone ssh://vcs-user@phabricator.tsi.ru:222/diffusion/T/tts.git, I use git Bash and can't specify key with -i private-key-file, but when I copy my id_rsa key to HOME/.ssh folder (git home I mean, "env" command helps me), it takes keys automatically (the name should be "id_rsa").

Maybe it is useful to modify documentation, i don't know.

Thank you very much for support!
