### ISSUE TITLE
Layout is broken on Blackbery Z10

### ISSUE THREAD

**Issue by andytruong** [phacility/phabricator#793]
It used to work fine.

![10491977_10153162567787122_8329299339830458471_n](https://cloud.githubusercontent.com/assets/41143/5888338/7e2a4e88-a42d-11e4-9609-41ff5ea6a322.jpg)

**Comment by epriestley** [comment]
Is `secure.phabricator.com` (which is running HEAD) also broken?

I don't think any of us have a Blackberry Z10, so we probably can't easily reproduce or fix this.

**Comment by chadlittle** [comment]
I'm curious what browser this is, right now we only support Chrome, Firefox, and Safari on mobile devices.

Blackberry looks free to test: http://us.blackberry.com/sites/developers/resources/simulators.html

**Comment by epriestley** [comment]
I also thought Blackberry went out of business, but I guess the only _mostly_ went out of business:

![screen shot 2015-01-24 at 10 09 45 am](https://cloud.githubusercontent.com/assets/102631/5888373/5e3fbd5a-a3b1-11e4-8f77-4690cda02903.png)

**Comment by chadlittle** [comment]
@andytruong that screenshot is the desktop layout. We detect and style mobile layouts differently. That detection code has not been in any recent changes (years).

**Comment by epriestley** [comment]
It looks like the simulator requires VMWare Fusion on OSX, which costs approximately as much as buying a phone.

**Comment by chadlittle** [comment]
I have fusion, trying to get the VM running now

**Comment by chadlittle** [comment]
I haven't been able to get it running in VMWare. The image mounts and launches, but the screen never displays so I'm stuck. Their forums don't seem to have much guidance other than I might be running an unsupported video card....

**Comment by chadlittle** [comment]
OK, I did get the simulator running on an older Mac I have. It's a stock install, launched "Browser" and went to https://secure.phabricator.com/

Layout works as expected, mobile menus are displaying. 

![screen shot 2015-01-24 at 11 31 06 am](https://cloud.githubusercontent.com/assets/1045295/5888646/b89fd9dc-a3bc-11e4-8a9f-1ed5740b9f66.png)

**Comment by andytruong** [comment]
Hi,

I have just install Phabricator for my team and tried to see how it works on my phone (:

> Is secure.phabricator.com (which is running HEAD) also broken?

No, secure.phabricator.com is good, but I found same issue with phabricator.wikimedia.org

**Comment by chadlittle** [comment]
Wikimedia renders correctly for me.

![screen shot 2015-01-24 at 11 47 14 am](https://cloud.githubusercontent.com/assets/1045295/5888698/c630ca82-a3be-11e4-9980-fc4557d83de8.png)
