### ISSUE TITLE
Phabricator behaves oddly when I do git cherry-pick -x

### ISSUE THREAD

**Issue by jcarrillo7** [phacility/phabricator#797]
Part of my team's workflow is to commit to a main branch and cherry pick the commit across to other branches that need it. These commits go in cleanly and as long as we do not sue the -x flag on git cherry-pick phabricator sees all these commits as the same and shows them under the closed review. Whenever we use the -x flag phabricator can no longer identify those commits with the review. Is there something special that happens with that flag that would confuse phabricator? 

This is a little annoying because I have a Herald rule set up to create Audits whenever a commit goes in without an accepted review and if anyone cherry-picks with -x it triggers an Audit even when it has already been reviewed. Is there a fix for this or is this proper behavior and I am just misunderstanding git?

**Comment by chadlittle** [comment]
We no longer trace bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
