### ISSUE TITLE
commit_hook.php hangs up

### ISSUE THREAD

**Issue by RuralHunter** [phacility/phabricator#799]
I updated phabricator to the latest code and found the newest commit_hook.php causes all commits hanging up and finally reports "Gateway timeout".
I found many commit-hook processes were hanging up like this:
1014     31633 31631 62 13:11 ?        00:00:55 /usr/bin/env TERM=dumb php /var/www/phabricator/bin/commit-hook FS pretxnchangegroup
This is the log in the error.log of nginx when client sided received "Gateway timeout":
2015/02/02 11:11:34 [error] 1115#0: *1679 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 116.226.*.*, server: phaserver, request: "POST /diffu
sion/FS/fs?cmd=unbundle HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "phaserver:8000"

I also checked the log of php5-fpm and phd and there was nothing. So I reviewed the change history of https://github.com/phacility/phabricator/commits/master/scripts/repository/commit_hook.php and found there were 2 changes these days. So I rolled  backup to the version(Jan 10, 2014) I used before the update of today and the problem went away.
I believe one of the latest 2 changes(Jan 28 and Jan 29, 2015) caused the problem.

**Comment by epriestley** [comment]
Try removing `TERM=dumb`.

If that fixes it, try figuring out why `TERM=dumb` causes a hang on your system. I've seen one other report of this, but we weren't able to figure out what the root cause of the hang was. I don't want to remove `TERM=dumb` without understanding the underlying problem because it fixes a different problem, and it makes no sense that it would cause a hang.

**Comment by RuralHunter** [comment]
Yes, it fixed the problem. Thanks! I will try to figuer it out.

**Comment by epriestley** [comment]
We got a third report of this, so the problem seems widespread enough to revert the change, even though we haven't been able to reproduce the issue. You can follow progress in https://secure.phabricator.com/T7119
