### ISSUE TITLE
Usage Exception: `arc set-config`  is only supported under git, hg, svn.

### ISSUE THREAD

**Issue by lianghu** [phacility/phabricator#800]
Hi,

We met a strange issue on a new workstation.  Any arc command will have silimar exception below,

     Usage Exception: `arc set-config`  is only supported under git, hg, svn.

However, the git is installed correctly on the linux machine, and the PHP also installed.

The log seems indicating the getvcstype return some empty value.

Do you know what's the problem?

P.S.  someone used root account successfully on that machine, now we're trying to use a non-root user account, and met such issue.

Thanks,
Lianghu

**Comment by chadlittle** [comment]
Is this resolved then @epriestley ?

**Comment by epriestley** [comment]
Yes, resolved at HEAD.
