### ISSUE TITLE
Phabricator fails with DB error after running daemons

### ISSUE THREAD

**Issue by abeerag** [phacility/phabricator#801]
I'd been running an older version of phabricator for a while. I just updated to tip of tree, following the setup instructions, and am seeing a strange error

A little while after starting the phab daemons, phabricator stops working with AphrontConnectionQueryException, complaining that "Attempt to connect to root@localhost failed with error #2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)." Restarting mysql does not help, and I need to reboot the machine

The delay is seemingly random, but might be connected with a harbormaster CI build. This workflow used to work fine beforehand. However, if I do not start the daemons, the setup works fine (minus all the daemon features of course)

**Comment by chadlittle** [comment]
Harbormaster is a prototype application: https://secure.phabricator.com/book/phabricator/article/prototypes/

What version of MySQL are you running (5.5 or later is recommended)

**Comment by abeerag** [comment]
I'm on  5.5.41-0ubuntu0.14.04.1

I didn't realize harbormaster was still in the prototype stage. I'll disable my CI integration for now and try and confirm if that was causing the bug.

**Comment by abeerag** [comment]
The issue actually seems to be independent of harbormaster. It essentially occurs a few minutes after I start the daemons. I can only resolve it by rebooting the machine

My apache log is as below:

[Tue Feb 03 22:57:06.541200 2015] [:error] [pid 1314] [client 10.0.83.251:60684] [2015-02-03 22:57:06] EXCEPTION: (AphrontConnectionQueryException) Attempt to connect to root@localhost failed with error #2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111). at [<phutil>/src/aphront/storage/connection/mysql/AphrontMySQLiDatabaseConnection.php:72]
[Tue Feb 03 22:57:06.542684 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #0 AphrontMySQLiDatabaseConnection::connect() called at [<phutil>/src/aphront/storage/connection/mysql/AphrontBaseMySQLDatabaseConnection.php:97]
[Tue Feb 03 22:57:06.542694 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #1 AphrontBaseMySQLDatabaseConnection::establishConnection() called at [<phutil>/src/aphront/storage/connection/mysql/AphrontBaseMySQLDatabaseConnection.php:120]
[Tue Feb 03 22:57:06.542700 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #2 AphrontBaseMySQLDatabaseConnection::requireConnection() called at [<phutil>/src/aphront/storage/connection/mysql/AphrontMySQLiDatabaseConnection.php:15]
[Tue Feb 03 22:57:06.542705 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #3 AphrontMySQLiDatabaseConnection::escapeBinaryString(string) called at [<phutil>/src/aphront/storage/connection/mysql/AphrontMySQLiDatabaseConnection.php:11]
[Tue Feb 03 22:57:06.542709 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #4 AphrontMySQLiDatabaseConnection::escapeUTF8String(string) called at [<phutil>/src/xsprintf/qsprintf.php:170]
[Tue Feb 03 22:57:06.542713 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #5 xsprintf_query(AphrontMySQLiDatabaseConnection, string, integer, string, integer) called at [<phutil>/src/xsprintf/xsprintf.php:63]
[Tue Feb 03 22:57:06.542717 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #6 xsprintf(string, AphrontMySQLiDatabaseConnection, array) called at [<phutil>/src/xsprintf/qsprintf.php:64]
[Tue Feb 03 22:57:06.542721 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #7 qsprintf(AphrontMySQLiDatabaseConnection, string, string, string, string, string)
[Tue Feb 03 22:57:06.542725 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #8 call_user_func_array(string, array) called at [<phutil>/src/xsprintf/queryfx.php:5]
[Tue Feb 03 22:57:06.542728 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #9 queryfx(AphrontMySQLiDatabaseConnection, string, string, string, string, string)
[Tue Feb 03 22:57:06.542732 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #10 call_user_func_array(string, array) called at [<phutil>/src/xsprintf/queryfx.php:16]
[Tue Feb 03 22:57:06.542743 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #11 queryfx_all(AphrontMySQLiDatabaseConnection, string, string, string, string, string)
[Tue Feb 03 22:57:06.542747 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #12 call_user_func_array(string, array) called at [<phutil>/src/xsprintf/queryfx.php:22]
[Tue Feb 03 22:57:06.542751 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #13 queryfx_one(AphrontMySQLiDatabaseConnection, string, string, string, string, string) called at [<phabricator>/src/applications/auth/engine/PhabricatorAuthSessionEngine.php:143]
[Tue Feb 03 22:57:06.542755 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #14 PhabricatorAuthSessionEngine::loadUserForSession(string, string) called at [<phabricator>/src/applications/base/controller/PhabricatorController.php:72]
[Tue Feb 03 22:57:06.542759 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #15 PhabricatorController::willBeginExecution() called at [<phabricator>/src/aphront/configuration/AphrontApplicationConfiguration.php:184]
[Tue Feb 03 22:57:06.542763 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #16 AphrontApplicationConfiguration::processRequest(AphrontRequest, PhutilDeferredLog, AphrontPHPHTTPSink) called at [<phabricator>/src/aphront/configuration/AphrontApplicationConfiguration.php:121]
[Tue Feb 03 22:57:06.542767 2015] [:error] [pid 1314] [client 10.0.83.251:60684]   #17 AphrontApplicationConfiguration::runHTTPRequest(AphrontPHPHTTPSink) called at [<phabricator>/webroot/index.php:19]

**Comment by chadlittle** [comment]
I'd maybe check mysql's logs, not sure why it'd go away, or at least I can't think of a reason Phabricator would cause it to go away. There are some database checks in the Config Application in Phabricator.

**Comment by abeerag** [comment]
I resolved the issue after checking the mysql logs. As part of the update process, I increased the memory utilization allowed by mysql. However, there wasn't enough RAM on the machine, and it would run out of memory when the daemon processes established database connections. I added more memory to the VM, and I have no problems now.
