### ISSUE TITLE
arc land should warn you when you are about to land a commit that differs from the approved revision

### ISSUE THREAD

**Issue by jcarrillo7** [phacility/phabricator#802]
Had this happen to a co-worker recently:

1) Started working on a bug fix on one computer
2) submitted a diff for review
3) had to change computers due to a computer failure
4) pulled his remote branch and submitted updates to the diff that were requested (never push his remote branch again)
5) got his old computer back after it was fixed
6) from his old computer he landed the bug fix but it landed the first commit in the revision without the later updates and fixes.

I think arc land should in this case at least have warned that the commit about to be landed differed from the final approved version on phabricator. Then he can have the choice of shooting himself in the foot or not. This was not noticed until a couple of days later and hunting down what happened was not immediately obvious. Arc can sometimes be a little too automatic and employees do not always understand whats going on (especially if they are new to the tools).

**Comment by chadlittle** [comment]
This isn't something that we'd pursue in the upstream. Mostly, it would catch 1 / 1000 errors, and cause friction 999/1000 other times.

https://secure.phabricator.com/book/phabcontrib/article/feature_requests/ covers a bit more in detail what we look for in feature requests.

IRC is a significantly better resource for understanding and modifying Phabricator to your companies specific needs. You can joins us as irc.freenode.net #phabricator.
